"""avatar hash

Revision ID: 00cf5297ed33
Revises: 71f9e4aa602f
Create Date: 2017-11-21 09:38:39.433065

"""

# revision identifiers, used by Alembic.
revision = '00cf5297ed33'
down_revision = '71f9e4aa602f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
