"""User confirm field added

Revision ID: 5e0da1c0cc86
Revises: f2e696ea92eb
Create Date: 2017-11-19 10:21:14.389665

"""

# revision identifiers, used by Alembic.
revision = '5e0da1c0cc86'
down_revision = 'f2e696ea92eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
